[project]
name = "etl"
version = "0.12.0"
description = "ETL package for the AGE-C project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "python-slugify>=8.0.4",
]

[dependency-groups]
dev = [
    "marimo>=0.13.13",
    "ruff>=0.11.5",
]
