export interface Item {
	slug: string;
	filmId: string;
	title: string;
	titleEn?: string;
	director: string;
	releaseType?: string | string[];
	releaseDate?: number;
	type?: string;
	releaseYear?: number;
	directorName?: string;
	directorBirthYear?: number;
	directorDeathYear?: number;
	directorGender?: string;
	directorNationality?: string;
	genre?: string[];
	trailerUrl?: string;
	posterUrl?: string;
	synopsis?: string;
	synopsisEn?: string;
	country?: string[];
	productionShare?: string[];
	tags?: string[];
	charId?: string;
	perId?: string | string[];
	charAge?: string;
	charGender?: string;
	charSexuality?: string;
	charOrigin?: string;
	charClass?: string;
	charProfession?: string | string[];
	charAbility?: string;
	assistedMobility?: string;
	perName?: string;
	perBirthYear?: number;
	perDeathYear?: number;
	perGender?: string;
	perNationality?: string;
	perRole?: string | string[];
}
