name: Build and deploy to pages

on:
  push:
    branches:
      - develop
      - main
      - research

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          bun install

      - name: Build
        env:
          GITHUB_ACTIONS_BUILD: true
        run: |
          bun run build

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./frontend/build
          github_token: ${{ secrets.GITHUB_TOKEN }}
